### ISSUE TITLE
Libxml

### ISSUE THREAD

**Issue by valguss** [Skywire/m2-actions-workflow#7]
Should `lib-libxml` be `libxml` in the php.yml

```
          extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip, lib-libxml
```

**Comment by Demoli** [comment]
Don't think it's needed anymore, it just throws a warning.

_____________________________________


*Neil Aitken*

Senior Magento Developer


SKYWIRE LONDON

Specialists in Fashion, Luxury & Lifestyle Ecommerce

T: +44 (0)20 7229 0202  www.skywire.co.uk


Get The Wire : Fashion Ecommerce Insights
<https://skywire.co.uk/author/skywire/>

**Comment by Demoli** [comment]
I don't have XML at all in the module actions installer, I suspect it doesn't need to be explicitly installed any more.

**Comment by valguss** [comment]
Now updated and merged in just in case
